version: '3'

services:
  telescopy:
    build:
      context: .
    image: wlatanowicz/telescopy
    restart: always
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /telescopy-storage:/app/pub
    ports:
      - "8000:8000"
      - "7624:7624"
    environment:
      - ENABLE_SIMULATORS=False
    privileged: true
    command: python server.py
